language: java

sudo: required

jdk:
  - oraclejdk8

install: echo LOL

script:
    - wget --user=guest --password=guest https://ci.wildfly.org/httpAuth/repository/downloadAll/WF_Nightly/.lastSuccessful/artifacts.zip
    - unzip -q artifacts.zip
    - export WILDFLY_DIST_ZIP=$(ls wildfly-*-SNAPSHOT.zip)
    - mvn install:install-file -DgroupId=org.wildfly -DartifactId=wildfly-dist -Dversion=11.0.0.elytron-SNAPSHOT -Dfile=$WILDFLY_DIST_ZIP -DgeneratePom=true -Dpackaging=zip
    - mvn verify -s settings.xml -B -fae -Dmaven.test.redirectTestOutputToFile=true -Dtest=**.elytron.**.* -Dversion.wildfly10=11.0.0.elytron-SNAPSHOT
